name: test-android-build

on:
  push:
    branches:
      - dev-android

jobs:
  build-android:
    name: Android Build Test
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Install Android Command Line Tools
        run: |
          mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools"
          cd "$ANDROID_SDK_ROOT/cmdline-tools"
          curl -sSLo commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
          unzip -q commandlinetools.zip
          rm commandlinetools.zip
          mv cmdline-tools latest

      - name: Accept Android SDK licenses
        run: yes | "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" --licenses

      - name: Install Android SDK packages
        run: |
          yes | "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" --update
          yes | "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" "platforms;android-36" "build-tools;36.0.0" "platform-tools"

      - name: Set environment variables for Android
        run: |
          echo "ANDROID_HOME=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "PATH=$PATH:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> $GITHUB_ENV

      - name: Prepare local.properties
        run: chmod +x android/append_local_properties.sh && sh android/append_local_properties.sh ${{ secrets.KEY_PASSWORD }} ${{ secrets.STORE_PASSWORD }}
        env:
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEYSTORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}

      - name: Get Flutter packages
        run: flutter pub get

      - name: Configure Gradle for build
        run: |
          echo "android.disableAutomaticComponentCreation=true" >> android/gradle.properties
          echo "android.lint.checkReleaseBuilds=false" >> android/gradle.properties

      - name: Build Android APK (common)
        run: flutter build apk --release --android-skip-build-dependency-validation

      - name: Build Android APK (split per ABI)
        run: flutter build apk --split-per-abi --android-skip-build-dependency-validation
