# This is a GitHub Actions configuration file

name: release-packages

on:
  push:
#    branches:
#      - dev
#      - main
    tags:
      - 'dev-v[0-9]+\.[0-9]+\.[0-9]+'
      - 'release-v[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  build-on-macos:
    name: Android, iOS, MacOS
    runs-on: macos-latest
    steps:
      - name: check code
        uses: actions/checkout@v3

      - name: set flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64 # optional, x64 or arm64
      - run: flutter pub get

      # Flutter ios ipa build command.
      - run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload

      - run: flutter build macos
      - run: |
          hdiutil create -format UDZO -srcfolder \
            build/macos/Build/Products/Release/whisper.app \
            build/macos/Build/Products/Release/whisper-x86_64.dmg

      # Upload assets to release
      - name: Push to Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/macos/Build/Products/Release/whisper-x86_64.dmg,build/ios/iphoneos/app.ipa"
          tag: ${{ github.ref_name }}
          token: ${{ secrets.TOKEN }}
          allowUpdates: true

  build-on-windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: check code
        uses: actions/checkout@v3

      - name: set flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter config --enable-windows-desktop
      - run: flutter build windows

      # New step to compress the build directory
      - name: Compress Release Build
        run: 7z a windows-release.zip ./build/windows/x64/runner/Release/*

      # Modified Push to Release step to upload the zip file
      - name: Push to Release
        uses: ncipollo/release-action@v1
        with:
          # Specify the path to the zip file instead of the folder
          artifacts: "windows-release.zip"
          tag: ${{ github.ref_name }}
          token: ${{ secrets.TOKEN }}
          allowUpdates: true

  build-on-linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - name: check code
        uses: actions/checkout@v3

      - name: set java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: set flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64 # optional, x64 or arm64

      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
          sudo apt-get install -y alien
      - run: flutter config --enable-linux-desktop
      - run: flutter build linux

      - name: set variable cur_version
        run: echo "cur_version=$(echo '${{github.ref_name}}' | cut -d'-' -f2 | sed 's/^v//')" >> $GITHUB_ENV

      # New step to compress the release bundle
      - name: build deb package
        run: chmod +x linux/build_deb.sh && sh linux/build_deb.sh $cur_version amd64
      - run: ls build/linux/deb
      - name: build rpm package
        run: sudo alien -r build/linux/deb/whisper-${cur_version}-amd64.deb && mv whisper-${cur_version}-2.x86_64.rpm whisper-${cur_version}.x86_64.rpm

      - run: echo "build deb/rpm finish"
      - run: pwd
      - run: ls build/linux/deb
      - run: flutter build apk
      - run: flutter build appbundle

      - run: echo "build apl/aar finish"
      - run: pwd
      - run: ls build/linux/deb

      # Modified Push to Release step to upload the tar.gz file
      - name: Push to Release
        uses: ncipollo/release-action@v1
        with:
          # Specify the path to the tar.gz file instead of the folder
          artifacts: "whisper-${{ env.cur_version }}.x86_64.rpm,build/linux/deb/whisper-${{ env.cur_version }}-amd64.deb,build/app/outputs/flutter-apk/*,build/app/outputs/bundle/release/app-release.aab"
          tag: ${{ github.ref_name }}
          token: ${{ secrets.TOKEN }}
          allowUpdates: true